version: 2
updates:
  # GitHub Actions
  - package-ecosystem: github-actions
    directory: '/'
    schedule:
      interval: 'weekly'
    assignees:
      - 'pandatix'

  # NPM development or production dependencies
  - package-ecosystem: npm
    directory: '/'
    schedule:
      interval: 'weekly'
    assignees:
      - 'pandatix'
